CREATE TABLE MESSAGES(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONTENT VARCHAR(256) NOT NULL,
    CREATED_ON DATE,
    CHANGED_ON DATE,
    DB_RECORD_CREATED_ON TIMESTAMP,
    DB_RECORD_CHANGED_ON TIMESTAMP
);